services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Despark\MindbodyBundle\Service\Soap\Services\ServiceMethodInterface:
            tags: [ mindbody.service.method ]
        Despark\MindbodyBundle\Service\Soap\Interfaces\CacheResponseInterface:
            tags: [ mindbody.cache.response ]

    Despark\MindbodyBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Exceptions,Model,Resources,MindbodyBundle.php}'

    # Main soap service
    Despark\MindbodyBundle\Service\SoapService:
        arguments: [ '@Despark\MindbodyBundle\Service\Soap\SoapAuthentication' ]
        shared: false

    Despark\MindbodyBundle\Model\Staff:
        shared: false

    Despark\MindbodyBundle\Model\MindbodyClass:
        shared: false

    Despark\MindbodyBundle\Model\Classes\ClassDescription:
        shared: false

    Despark\MindbodyBundle\Model\Client:
        shared: false

    Despark\MindbodyBundle\Model\StaffInterface: '@Despark\MindbodyBundle\Model\Staff'

    Despark\MindbodyBundle\Model\MindbodyClassInterface: '@Despark\MindbodyBundle\Model\MindbodyClass'

    Despark\MindbodyBundle\Model\ClientInterface: '@Despark\MindbodyBundle\Model\Client'

    # Soap Methods
    Despark\MindbodyBundle\Service\Soap\Services\ClassService\GetEnrollments:
        arguments: ['@Despark\MindbodyBundle\Service\SoapService', '@Despark\MindbodyBundle\Service\Soap\Services\ClassService\GetEnrollments\GetEnrollmentResponseParser']

    Despark\MindbodyBundle\Service\Soap\Services\SiteService\GetLocations:
        arguments: ['@Despark\MindbodyBundle\Service\SoapService', '@Despark\MindbodyBundle\Service\Soap\Services\SiteService\GetLocations\GetLocationsResponseParser', '@cache.app']

    Despark\MindbodyBundle\Service\Soap\Services\StaffService\GetStaff:
        arguments: ['@Despark\MindbodyBundle\Service\SoapService', '@Despark\MindbodyBundle\Service\Soap\Services\StaffService\Parsers\StaffResponseParser']

    Despark\MindbodyBundle\Service\Soap\Services\StaffService\AddOrUpdateStaff:
        arguments: ['@Despark\MindbodyBundle\Service\SoapService', '@Despark\MindbodyBundle\Service\Soap\Services\StaffService\Parsers\StaffResponseParser']

    Despark\MindbodyBundle\Service\Soap\Services\ClassService\GetClasses:
        arguments: ['@Despark\MindbodyBundle\Service\SoapService', '@Despark\MindbodyBundle\Service\Soap\Services\ClassService\Parsers\GetClassesResponseParser']

    Despark\MindbodyBundle\Service\Soap\Services\ClassService\GetClassDescriptions:
        arguments: ['@Despark\MindbodyBundle\Service\SoapService', '@Despark\MindbodyBundle\Service\Soap\Services\ClassService\Parsers\GetClassDescriptionsResponseParser']

    Despark\MindbodyBundle\Service\Soap\Services\ClientService\GetClients:
        arguments: ['@Despark\MindbodyBundle\Service\SoapService', '@Despark\MindbodyBundle\Service\Soap\Services\ClientService\Parsers\GetClientsResponseParser']

